# Generated by Django 4.2.24 on 2025-09-14 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                            ("upload_csv", "Subida de CSV"),
                            ("generate_report", "Generación de reporte"),
                            ("download_report", "Descarga de reporte"),
                            ("view_dashboard", "Ver dashboard"),
                            ("api_call", "Llamada API"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad de Usuario",
                "verbose_name_plural": "Actividades de Usuario",
                "db_table": "analytics_activity",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type"],
                        name="analytics_a_user_id_4da67b_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_a_timesta_5cba5c_idx"
                    ),
                ],
            },
        ),
    ]
