# Generated by Django 4.2.24 on 2025-09-14 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("pdf", "PDF"),
                            ("image", "Imagen"),
                            ("document", "Documento"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("container_name", models.CharField(max_length=100)),
                ("blob_name", models.CharField(max_length=255, unique=True)),
                ("blob_url", models.URLField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("tags", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de Storage",
                "verbose_name_plural": "Archivos de Storage",
                "db_table": "storage_file",
                "ordering": ["-upload_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "file_type"],
                        name="storage_fil_user_id_e7c9b8_idx",
                    ),
                    models.Index(
                        fields=["upload_date"], name="storage_fil_upload__7e781c_idx"
                    ),
                    models.Index(
                        fields=["blob_name"], name="storage_fil_blob_na_2fb714_idx"
                    ),
                ],
            },
        ),
    ]
