# Generated by Django 4.2.24 on 2025-09-14 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(default="text/csv", max_length=100)),
                ("azure_blob_url", models.URLField(blank=True)),
                ("azure_blob_name", models.CharField(blank=True, max_length=255)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("rows_count", models.PositiveIntegerField(blank=True, null=True)),
                ("columns_count", models.PositiveIntegerField(blank=True, null=True)),
                ("analysis_data", models.JSONField(default=dict)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo CSV",
                "verbose_name_plural": "Archivos CSV",
                "db_table": "reports_csvfile",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("executive", "Ejecutivo"),
                            ("detailed", "Detallado"),
                            ("summary", "Resumen"),
                            ("custom", "Personalizado"),
                        ],
                        default="executive",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("expired", "Expirado"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("analysis_data", models.JSONField(default=dict)),
                ("pdf_file_url", models.URLField(blank=True)),
                ("html_preview_url", models.URLField(blank=True)),
                ("pdf_azure_blob_name", models.CharField(blank=True, max_length=255)),
                ("user_prompt", models.TextField(blank=True)),
                ("generation_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_time_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("file_size_mb", models.FloatField(blank=True, null=True)),
                ("pages_count", models.PositiveIntegerField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "csv_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="reports.csvfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "db_table": "reports_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="reports_rep_user_id_8456e4_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_rep_created_a6aabf_idx"
                    ),
                    models.Index(
                        fields=["report_type"], name="reports_rep_report__dbb097_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="csvfile",
            index=models.Index(
                fields=["user", "processing_status"],
                name="reports_csv_user_id_b888dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="csvfile",
            index=models.Index(
                fields=["upload_date"], name="reports_csv_upload__620c8e_idx"
            ),
        ),
    ]
