# Generated by Django 4.2.24 on 2025-09-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_csvfile_analysis_data_and_more'),
        ('reports', '0003_fix_csv_file_constraint'),
    ]

    operations = [
    ]
