# Generated by Django 4.2.24 on 2025-09-17 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_merge_20250917_1658'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_csv_fil_3c2bfd_idx',
            old_name='reports_rep_csv_fil_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='file_size_mb',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generation_config',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_downloaded_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pdf_azure_blob_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_prompt',
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='html_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('executive', 'Ejecutivo'), ('detailed', 'Detallado'), ('summary', 'Resumen'), ('comprehensive', 'Análisis Completo'), ('custom', 'Personalizado')], default='executive', max_length=20),
        ),
    ]
